spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce?useSSL=false&serverTimezone=UTC
    username: root
    password: A25042020#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect